--Initial user rights.

BEGIN TRANSACTION;

REVOKE ALL ON SCHEMA sec FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA sec FROM "phenodb_reader";
REVOKE ALL ON SCHEMA sec FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA sec FROM "phenodb_user";
REVOKE ALL ON SCHEMA sec FROM "phenodb_coworker";
REVOKE ALL ON ALL TABLES IN SCHEMA sec FROM "phenodb_coworker";

REVOKE ALL ON SCHEMA coh FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_reader";
REVOKE ALL ON SCHEMA coh FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_user";

REVOKE ALL ON SCHEMA sum FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_reader";
REVOKE ALL ON SCHEMA sum FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_user";

REVOKE ALL ON SCHEMA met FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_reader";
REVOKE ALL ON SCHEMA met FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_user";


/**phenodb_owner**/

REVOKE ALL ON SCHEMA met FROM "phenodb_owner";
GRANT ALL ON SCHEMA met TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA met TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_owner";

--ALTER DEFAULT PRIVILEGES IN SCHEMA met
--GRANT EXECUTE ON FUNCTIONS
--TO "phenodb_owner";

--ALTER DEFAULT PRIVILEGES IN SCHEMA met
--GRANT USAGE ON TYPES
--TO "phenodb_owner";

--GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA met TO "phenodb_owner";

REVOKE ALL ON SCHEMA sum FROM "phenodb_owner";
GRANT ALL ON SCHEMA sum TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA sum TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA sum FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA sum TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA sum FROM "phenodb_owner";

REVOKE ALL ON SCHEMA coh FROM "phenodb_owner";
GRANT ALL ON SCHEMA coh TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA coh
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA coh TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA coh FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA coh
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA coh TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA coh FROM "phenodb_owner";

REVOKE ALL ON SCHEMA sec FROM "phenodb_owner";
GRANT ALL ON SCHEMA sec TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA sec FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA sec
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA sec TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA sec FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA sec
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA sec TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA sec FROM "phenodb_owner";


/**phenodb_coworker**/

REVOKE ALL ON SCHEMA met FROM "phenodb_coworker";
GRANT ALL ON SCHEMA met TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA met TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_coworker";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_coworker";


REVOKE ALL ON SCHEMA sum FROM "phenodb_coworker";
GRANT ALL ON SCHEMA sum TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA sum TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA sum FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA sum TO "phenodb_coworker";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA sum FROM "phenodb_coworker";

REVOKE ALL ON SCHEMA coh FROM "phenodb_coworker";
GRANT ALL ON SCHEMA coh TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA coh
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA coh TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA coh FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA coh
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA coh TO "phenodb_coworker";


/**phenodb_user**/

REVOKE ALL ON SCHEMA met FROM "phenodb_user";
GRANT ALL ON SCHEMA met TO "phenodb_user"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT ON TABLES TO "phenodb_user";
GRANT SELECT ON ALL TABLES IN SCHEMA met TO "phenodb_user";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_user";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_user";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_user";


REVOKE ALL ON SCHEMA sum FROM "phenodb_user";
GRANT ALL ON SCHEMA sum TO "phenodb_user"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT ON TABLES TO "phenodb_user";
GRANT SELECT ON ALL TABLES IN SCHEMA sum TO "phenodb_user";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA sum FROM "phenodb_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_user";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA sum TO "phenodb_user";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA sum FROM "phenodb_user";

REVOKE ALL ON SCHEMA coh FROM "phenodb_user";
GRANT ALL ON SCHEMA coh TO "phenodb_user"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_user";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA coh FROM "phenodb_user";

/**phenodb_reader**/

REVOKE ALL ON SCHEMA met FROM "phenodb_reader";
GRANT ALL ON SCHEMA met TO "phenodb_reader"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT ON TABLES TO "phenodb_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA met TO "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_reader";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_reader";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_user";


REVOKE ALL ON SCHEMA sum FROM "phenodb_reader";
GRANT ALL ON SCHEMA sum TO "phenodb_reader"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA sum FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT ON TABLES TO "phenodb_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA sum TO "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA sum FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA sum
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_reader";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA sum TO "phenodb_reader";

REVOKE ALL ON SCHEMA coh FROM "phenodb_reader";

REVOKE ALL ON ALL TABLES IN SCHEMA coh FROM "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA coh FROM "phenodb_reader";

REVOKE ALL ON ALL FUNCTIONS IN SCHEMA coh FROM "phenodb_reader";

--for sumstats_old
/*
GRANT ALL ON SCHEMA sumstat_old TO "phenodb_coworker"; -- WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA sumstat_old
GRANT SELECT ON TABLES TO "phenodb_coworker";
GRANT SELECT ON ALL TABLES IN SCHEMA sumstat_old TO "phenodb_coworker";
*/
COMMIT;
