--Initial user rights.

BEGIN TRANSACTION;

REVOKE ALL ON SCHEMA dat_protected FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_protected FROM "phenodb_reader";
REVOKE ALL ON SCHEMA dat_protected FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_protected FROM "phenodb_user";
REVOKE ALL ON SCHEMA dat_protected FROM "phenodb_coworker";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_protected FROM "phenodb_coworker";

REVOKE ALL ON SCHEMA dat_cohort FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_cohort FROM "phenodb_reader";
REVOKE ALL ON SCHEMA dat_cohort FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_cohort FROM "phenodb_user";

REVOKE ALL ON SCHEMA dat_summary FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_summary FROM "phenodb_reader";
REVOKE ALL ON SCHEMA dat_summary FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA dat_summary FROM "phenodb_user";

REVOKE ALL ON SCHEMA met FROM "phenodb_reader";
REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_reader";
REVOKE ALL ON SCHEMA met FROM "phenodb_user";
REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_user";


/**phenodb_owner**/

REVOKE ALL ON SCHEMA met FROM "phenodb_owner";
GRANT ALL ON SCHEMA met TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA met TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_owner";

--ALTER DEFAULT PRIVILEGES IN SCHEMA met
--GRANT EXECUTE ON FUNCTIONS
--TO "phenodb_owner";

--ALTER DEFAULT PRIVILEGES IN SCHEMA met
--GRANT USAGE ON TYPES
--TO "phenodb_owner";

--GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA met TO "phenodb_owner";

REVOKE ALL ON SCHEMA dat_summary FROM "phenodb_owner";
GRANT ALL ON SCHEMA dat_summary TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_summary FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA dat_summary TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_summary FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA dat_summary TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_summary FROM "phenodb_owner";

REVOKE ALL ON SCHEMA dat_cohort FROM "phenodb_owner";
GRANT ALL ON SCHEMA dat_cohort TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_cohort FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA dat_cohort TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_cohort FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA dat_cohort TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_cohort FROM "phenodb_owner";

REVOKE ALL ON SCHEMA dat_protected FROM "phenodb_owner";
GRANT ALL ON SCHEMA dat_protected TO "phenodb_owner"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_protected FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_protected
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_owner";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA dat_protected TO "phenodb_owner";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_protected FROM "phenodb_owner";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_protected
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_owner";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA dat_protected TO "phenodb_owner";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_protected FROM "phenodb_owner";


/**phenodb_coworker**/

REVOKE ALL ON SCHEMA met FROM "phenodb_coworker";
GRANT ALL ON SCHEMA met TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA met TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_coworker";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_coworker";


REVOKE ALL ON SCHEMA dat_summary FROM "phenodb_coworker";
GRANT ALL ON SCHEMA dat_summary TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_summary FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA dat_summary TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_summary FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA dat_summary TO "phenodb_coworker";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_summary FROM "phenodb_coworker";

REVOKE ALL ON SCHEMA dat_cohort FROM "phenodb_coworker";
GRANT ALL ON SCHEMA dat_cohort TO "phenodb_coworker"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_cohort FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_coworker";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA dat_cohort TO "phenodb_coworker";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_cohort FROM "phenodb_coworker";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_coworker";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA dat_cohort TO "phenodb_coworker";

/**phenodb_user and phenodb_reader**/

REVOKE ALL ON SCHEMA met FROM "phenodb_reader";
GRANT ALL ON SCHEMA met TO "phenodb_reader"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA met FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "phenodb_reader";
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA met TO "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA met FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA met
GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO "phenodb_reader";
GRANT SELECT, UPDATE, USAGE ON ALL SEQUENCES IN SCHEMA met TO "phenodb_reader";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA met FROM "phenodb_reader";


REVOKE ALL ON SCHEMA dat_summary FROM "phenodb_reader";
GRANT ALL ON SCHEMA dat_summary TO "phenodb_reader"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_summary FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT SELECT ON TABLES TO "phenodb_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA dat_summary TO "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_summary FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_summary
GRANT SELECT, USAGE ON SEQUENCES TO "phenodb_reader";
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA dat_summary TO "phenodb_reader";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_summary FROM "phenodb_reader";

REVOKE ALL ON SCHEMA dat_cohort FROM "phenodb_reader";
GRANT ALL ON SCHEMA dat_cohort TO "phenodb_reader"; -- WITH GRANT OPTION;

REVOKE ALL ON ALL TABLES IN SCHEMA dat_cohort FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT SELECT ON TABLES TO "phenodb_reader";
GRANT SELECT ON ALL TABLES IN SCHEMA dat_cohort TO "phenodb_reader";

REVOKE ALL ON ALL SEQUENCES IN SCHEMA dat_cohort FROM "phenodb_reader";
ALTER DEFAULT PRIVILEGES IN SCHEMA dat_cohort
GRANT SELECT, USAGE ON SEQUENCES TO "phenodb_reader";
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA dat_cohort TO "phenodb_reader";

--REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dat_cohort FROM "phenodb_reader";



COMMIT;
